log:
  level: INFO
  format: "%(asctime)s %(levelname)-8s %(threadName)-15s %(name)s:%(lineno)-3s %(message)s"
font_locations:
  - "~/sync/resources/fonts"
symlinks:
  "~/sync/resources/config/alacritty": "~/.config/alacritty"
  "~/sync/resources/config/alfred": "~/.config/Alfred.alfredpreferences"
  "~/sync/resources/config/aws": "~/.aws"
  "~/sync/resources/config/gitconfig": "~/.gitconfig"
  "~/sync/resources/config/profile": "~/.profile"
  "~/sync/resources/config/rofi": "~/.config/rofi"
  "~/sync/resources/config/ssh/ab": "~/.ssh/ab"
  "~/sync/resources/config/ssh/akatovda": "~/.ssh/akatovda"
  "~/sync/resources/config/ssh/config": "~/.ssh/config"
  "~/sync/resources/config/wakerc": "~/.wakerc"
  "~/sync/resources/config/xinitrc": "~/.xinitrc"
  "~/sync/resources/config/xsession": "~/.xsession"
  "~/sync/resources/config/zshrc": "~/.zshrc"
  "~/sync/resources/config/cabal/config": "~/.config/cabal/config"
  "~/sync/resources/config/htop/htoprc": "~/.config/htop/htoprc"
  "~/sync/resources/config/karabiner": "~/.config/karabiner"
  "~/sync/resources/config/nix": "~/.config/nix"
  "~/sync/resources/config/openemu": "~/Game Library"
  "~/sync/resources/config/applications": "~/.local/share/applications"
  # "~/sync/resources/config/autostart": "~/.config/autostart"
  "~/sync/resources/config/terminator": "~/.config/terminator"
  "~/sync/resources/config/cinnamon": "~/.config/cinnamon"
  "~/sync/resources/ice": "~/.local/share/ice"
  "~/sync/resources/documents": "~/Documents"
  "~/sync/resources/camera": "~/Pictures"
  "~/sync/resources/dotfiles/redshift.conf": "~/.config/redshift.conf"
views:
  remote: "ssh://git-codecommit.us-east-2.amazonaws.com/v1/repos/views"
  local: "~/sync/views"
